import type { Metadata } from "next";
import { TypekitLoader } from "@/components/TypekitLoader";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";

import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="font-[fot-tsukuardgothic-std] antialiased">
        <ThemeProvider>
          <TypekitLoader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
