import type { Metadata } from "next";
import { TypekitLoader } from "@/components/TypekitLoader";
import "./globals.css";

import Head from "next/head";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased">
        <TypekitLoader />
        {children}
      </body>
    </html>
  );
}
