import type { Metadata } from "next";
import { TypekitLoader } from "@/components/TypekitLoader";
import { ThemeProvider } from "@/components/ThemeProvider";

import "./globals.css";
import 'zenn-content-css';

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <script src="https://embed.zenn.studio/js/listen-embed-event.js"></script>
      </head>
      <body className="font-[fot-tsukuardgothic-std] antialiased text-black dark:text-white bg-white dark:bg-black">
        {/* <ThemeProvider> */}
          <TypekitLoader />
          <Header />
          {children}
          <Footer />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
